from typing import List, Optional
from pydantic import BaseModel, Field

# ─────────────────────────────────────────────
# TWO-PASS SCHEMA
# ─────────────────────────────────────────────

class Pass1Extraction(BaseModel):
    """Raw extraction from document chunks. Highly flexible."""
    component_name: Optional[str] = Field(None, description="Part name as written in the text")
    material_specifications: Optional[List[str]] = Field(None, description="Material codes or grades")
    certifications_mentioned: Optional[List[str]] = Field(None, description="List of certifications found (e.g., ISO, IATF)")
    weight_and_dimensions: Optional[str] = Field(None, description="Weight and dimension strings")
    surface_treatments: Optional[List[str]] = Field(None, description="Surface treatments mentioned")

class PartClassification(BaseModel):
    category: str = Field(..., description="e.g., Powertrain, Interior, Chassis")
    name: str = Field(..., description="Normalized part name")

class SearchParameters(BaseModel):
    must_have_processes: List[str] = Field(..., description="Inferred manufacturing processes")
    material_families: List[str] = Field(..., description="Broad material categories")

class Compliance(BaseModel):
    required_certs: List[str] = Field(..., description="Standard quality certifications")
    environmental: List[str] = Field(..., description="Environmental standards")

class SupplierSearchProfile(BaseModel):
    """Final synthesized profile generated by The Organizer."""
    part_classification: PartClassification
    search_parameters: SearchParameters
    compliance: Compliance
    generated_search_persona: str = Field(..., description="2-3 sentence semantic description of the ideal supplier")
